name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: getpagespeed/rpmbuilder:centos-8
    steps:
    - uses: actions/checkout@v2
    - name: What OS is running
      run: uname -a
    - name: Build the .spec file
      run: build
