name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: getpagespeed/rpmbuilder:centos-8
    steps:
    - uses: actions/checkout@v2

    - name: Copy spec to root
      run: pwd; cp packaging/rhel/*.spec ./; ls -al

    - name: Set up release-like archive from checkout
      run: pwd; packaging/version-from-tag.sh; ls -al

    - name: Ensure /sources are symlinked to this directory
      run: cp -aR ./* /sources/

    - name: Build the .spec file
      run: mkdir -p /github/home/rpmbuild/{SOURCES,SPECS}/; pwd; ls -al; cd /sources/ && pwd && ls -al &&  build
