name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: getpagespeed/rpmbuilder:centos-8
    steps:
    - uses: actions/checkout@v2
    - name: Copy spec to root
      run: cp packaging/rhel/*.spec ./; ls -al
    - name: Set up release-like archive from checkout
      run: packaging/version-from-tag.sh; ls -al
    - name: Build the .spec file
      run: ls -al; build
