name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: getpagespeed/rpmbuilder:centos-8
    steps:
    - uses: actions/checkout@v2
    - name: Ensure /sources are symlinked to this directory
      run: rm -rf /sources && ln -fs $(pwd) /sources
    - name: Copy spec to root
      run: pwd; cp packaging/rhel/*.spec ./; ls -al
    - name: Set up release-like archive from checkout
      run: pwd; packaging/version-from-tag.sh; ls -al
    - name: Build the .spec file
      run: pwd; ls -al; build
